fos_rest:
    view:
        view_response_listener: true
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
    format_listener:
        rules:
           - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    routing_loader:
        default_format: json
        include_format: false

